### ISSUE TITLE
[CRASH] Null Object Reference

### ISSUE THREAD

**Issue by polybiusproxy** [gedehari/IzzyEngine#19]
![image](https://user-images.githubusercontent.com/47796739/130240323-df046f31-7cd1-4040-834f-cd7f915ce360.png)
Happened when selecting Tutorial on Freeplay menu.

**Comment by gedehari** [comment]
Oh yeah this is because I haven't coded that part where it shouldn't spawn "dad", since "dad" is not defined in Tutorial. Will fix this later, thanks for reporting.

**Comment by Alittletrolling** [comment]
I shall fix it

**Comment by Alittletrolling** [comment]
oh hey the first ever actual issue

**Comment by gedehari** [comment]
Fixed in 682b4cc73fe2a21b7eeb80eb23650af2b694f1a3
