### ISSUE TITLE
another cool function for u to use!

### ISSUE THREAD

**Issue by ahazywinter** [gedehari/IzzyEngine#21]
It might be dumb, since you can just do
```hx
if (curBeat % num == 0 && curSong == 'Tutorial') {
   someFunc();
}
```

but this shortens it by a bit, so if yer lazy :)

```hx
function onBeat(number:Int, result:Int, _curSong:String):Bool 
    return curBeat % number == result && curSong == _curSong ? true : false;

// Heres an example:

if (onBeat(4, 0, 'Tutorial')) {
    trace('test!!');
}
```

If you dont want me to give any help plz just tell me!

**Comment by gedehari** [comment]
Oh yeah this could be useful for Vanilla amd Kade Engine modding, mine doesn't use that as it's a complete recreation of Funkin and it's completely different. Thank you nonetheless!
