### ISSUE TITLE
is this engine dead?

### ISSUE THREAD

**Issue by Stilic** [gedehari/IzzyEngine#29]
ayo should i do something for restore this cool shit???

**Comment by Stilic** [comment]
also maybe i will test this soon!

**Comment by gedehari** [comment]
maybe? But I don't plan on continuing this engine for some time now, as I have other projects to work on,
Issue's not closed until I work on it again

**Comment by gedehari** [comment]
For now, I have no plans to continue Izzy Engine, as I am already working
on another engine (will be open sourced later). Thank you for your concern.
