### ISSUE TITLE
How to compile the crash handler?

### ISSUE THREAD

**Issue by lunarcleint** [gedehari/IzzyEngine#32]
When I run the bat it doesn't compile it. I might be mad dumb but I downloaded everything to compile Haxe UI apps. Can we get a guide or something?

**Comment by gedehari** [comment]
I am considering changing the crash handler code to something else as using hxWidgets is proven to be too much of a hassle (plus it produces quite a big binary for a simple crash handler). I'll think of something whenever I have time to get to this project.
